FilesMetadataConsoleBuildLive:
  variables:
    GIGADB_ENV: "live"
    YII_DEBUG: "true"
  stage: live build
  tags:
    - $GITLAB_USER_LOGIN
  needs: ["FilesMetaDataConsoleDeployStaging"]
  extends: .tag_only
  when: manual
  environment:
    name: "live"
    url: $REMOTE_HOME_URL
  script:
    # Load Base image
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
    - docker load -i php-8.2.3-cli-bullseye.tar
    - docker load -i php-$PHP_VERSION-fpm-buster.tar
    - docker load -i php-$PHP_VERSION-cli-buster.tar
    - docker load -i alpine-3_14.tar
    - docker load -i nginx-$NGINX_VERSION-alpine.tar
    - docker load -i node-$NODE_VERSION-buster-slim.tar
    # login to gitlab container registry
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    # build for production
    - echo "Building app"
    - cp .secrets gigadb/app/tools/files-metadata-console/
    - cp .env gigadb/app/tools/files-metadata-console/
    - cd gigadb/app/tools/files-metadata-console
    - docker pull registry.gitlab.com/$CI_PROJECT_PATH/production-files-metadata-console:latest || true
    - docker-compose -f ./docker-compose.yml run --rm configure
    - docker-compose -f ./docker-compose.yml run --rm composer install
    - docker-compose -f ./docker-compose.production-envs.yml build production-files-metadata-console
    - docker tag ${CI_PROJECT_NAME}_production-files-metadata-console:latest registry.gitlab.com/$CI_PROJECT_PATH/production-files-metadata-console:$GIGADB_ENV
    - docker push registry.gitlab.com/$CI_PROJECT_PATH/production-files-metadata-console:$GIGADB_ENV
  artifacts:
    untracked: true
    when: always
    expire_in: 1 week
