---
# build a Centos server running a secure Docker CE install

- name: Setup Fail2ban
  hosts: all

  tasks:
    - debug:
        msg: "remote private ip : {{ ec2_private_ip }}"

  roles:
    - role: ../../roles/fail2ban
    - role: ../../roles/jail-ssh

- name: Setup Docker CE
  hosts: all


  roles:
    - role: ../../roles/docker-install
    - role: role-secure-docker-daemon
      dds_host: "{{ inventory_hostname }}"
      dds_server_cert_path: /etc/docker
      dds_restart_docker: no
      dds_client_cert_path: /home/centos/.docker
    - role: ../../roles/docker-postinstall
    - role: ../../roles/postgres-preinstall
    - role: ansible-role-postgresql
      postgresql_enablerepo: "pgdg96"
      postgresql_version: 9.6
      postgresql_data_dir: /var/lib/pgsql/9.6/data
      postgresql_bin_path: /usr/pgsql-9.6/bin
      postgresql_config_path: /var/lib/pgsql/9.6/data
      postgresql_daemon: postgresql-9.6.service
      postgresql_packages:
        - postgresql96
        - postgresql96-server
        - postgresql96-libs
        - postgresql96-contrib
        - postgresql96-devel
      postgresql_users:
      - name: "{{ pg_user }}"
        password: "{{ pg_password}}"
      postgresql_databases:
      - name: "{{ pg_database}}"
      - name: "fuw"
      postgresql_global_config_options:
      - option: listen_addresses
        value: '*'
      postgresql_hba_entries:
      - { type: local, database: all, user: all, auth_method: trust }
      - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
      - { type: host, database: all, user: all, address: '::1/128', auth_method: md5 }
      - { type: host, database: all, user: all, address: 'samenet', auth_method: md5 }
    - role: ../../roles/postgres-postinstall
    - role: ../../roles/fuw
